# Generated by Django 5.1.3 on 2024-12-11 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_baseproduct_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseproduct',
            name='user',
        ),
    ]
