# Generated by Django 5.1.3 on 2024-12-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_is_farmer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_farmer',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
